/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ItemVendidoDAO;
import dao.ProdutoDAO;
import dao.VendaDAO;
import java.awt.Toolkit;
import java.util.Arrays;
import java.util.Collections;
import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import modelo.ItemVendido;
import modelo.Produto;
import modelo.Venda;

/**
 *
 * @author Cliente
 */
public class CaixaVendaGUI extends javax.swing.JFrame {

    int j = 0;
    float valorTotalVenda = 0;
    String tamanho;
    int N250 = 0;
    int N500 = 0;
    int N750 = 0;
    int NBiscoito = 0;
    int NBatata = 0;

    public CaixaVendaGUI() {
        initComponents();
        setIcon();
        jComboBoxSabor1.setEnabled(false);
        jComboBoxSabor2.setEnabled(false);
        jComboBoxSabor3.setEnabled(false);
        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> listaSabor = dao.recuperaSaboresDisponiveis();
        ProdutoDAO dao2 = new ProdutoDAO();
        List<Produto> listaExtra = dao2.recuperaExtrasDisponiveis();
        jComboBoxSabor1.addItem("-");
        jComboBoxSabor2.addItem("-");
        jComboBoxSabor3.addItem("-");
        jComboBoxExtras.addItem("-");
        for (int i = 0; i < listaSabor.size(); i++) {
            jComboBoxSabor1.addItem(listaSabor.get(i).getEspecificacao());
            jComboBoxSabor2.addItem(listaSabor.get(i).getEspecificacao());
            jComboBoxSabor3.addItem(listaSabor.get(i).getEspecificacao());
        }
        for (int i = 0; i < listaExtra.size(); i++) {
            jComboBoxExtras.addItem(listaExtra.get(i).getEspecificacao());
        }
        DefaultTableModel modelo = (DefaultTableModel) this.jTableVenda.getModel();
        int[] rows = jTableVenda.getSelectedRows();

        for (int i = 0; i < rows.length; i++) {
            modelo.removeRow(rows[i] - i);
        }

        for (int row = 0; row < modelo.getRowCount(); row++) {
            jTableVenda.setValueAt(row + 1, row, 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTamanho = new javax.swing.ButtonGroup();
        jLabelTamanho = new javax.swing.JLabel();
        jRadioButton250ml = new javax.swing.JRadioButton();
        jRadioButton500ml = new javax.swing.JRadioButton();
        jRadioButton750ml = new javax.swing.JRadioButton();
        jLabelSabor1 = new javax.swing.JLabel();
        jLabelSabor2 = new javax.swing.JLabel();
        jLabelSabor3 = new javax.swing.JLabel();
        jComboBoxSabor1 = new javax.swing.JComboBox();
        jComboBoxSabor2 = new javax.swing.JComboBox();
        jComboBoxSabor3 = new javax.swing.JComboBox();
        jLabelDesconto = new javax.swing.JLabel();
        jLabelValorUnit = new javax.swing.JLabel();
        jTextFieldValorUnitSuco = new javax.swing.JTextField();
        jTextFieldQtdSuco = new javax.swing.JTextField();
        jLabelQtd = new javax.swing.JLabel();
        jButtonAdicionarSuco = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabelExtras = new javax.swing.JLabel();
        jComboBoxExtras = new javax.swing.JComboBox();
        jButtonExtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVenda = new javax.swing.JTable();
        jLabelValorTot = new javax.swing.JLabel();
        jTextFieldValorTot = new javax.swing.JTextField();
        jLabelValorPago = new javax.swing.JLabel();
        jTextFieldValorPago = new javax.swing.JTextField();
        jLabelTroco = new javax.swing.JLabel();
        jButtonEfetuarVenda = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelNSucos = new javax.swing.JLabel();
        jTextFieldNSucos = new javax.swing.JTextField();
        jTextFieldTroco = new javax.swing.JTextField();
        jTextFieldQtdExtra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldValorUnitExtra = new javax.swing.JTextField();
        jTextFieldTotalItens = new javax.swing.JTextField();
        jFormattedTextFieldDesconto = new javax.swing.JTextField();
        jTextFieldDescontoTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTamanho.setText("Tamanho:");

        buttonGroupTamanho.add(jRadioButton250ml);
        jRadioButton250ml.setText("250ml");
        jRadioButton250ml.setActionCommand("250ml");
        jRadioButton250ml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton250mlActionPerformed(evt);
            }
        });

        buttonGroupTamanho.add(jRadioButton500ml);
        jRadioButton500ml.setText("500ml");
        jRadioButton500ml.setActionCommand("500ml");
        jRadioButton500ml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton500mlActionPerformed(evt);
            }
        });

        buttonGroupTamanho.add(jRadioButton750ml);
        jRadioButton750ml.setText("750ml");
        jRadioButton750ml.setActionCommand("750ml");
        jRadioButton750ml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton750mlActionPerformed(evt);
            }
        });

        jLabelSabor1.setText("Sabor 1:");

        jLabelSabor2.setText("Sabor 2:");

        jLabelSabor3.setText("Sabor 3:");

        jLabelDesconto.setText("Desconto: R$");

        jLabelValorUnit.setText("Valor unit.: R$");

        jTextFieldValorUnitSuco.setEditable(false);

        jTextFieldQtdSuco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldQtdSucoKeyTyped(evt);
            }
        });

        jLabelQtd.setText("Quantidade:");

        jButtonAdicionarSuco.setText("Adicionar Suco");
        jButtonAdicionarSuco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarSucoActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setToolTipText("Limpa os campos referentes à adicionar sucos");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jLabelExtras.setText("Extras:");

        jButtonExtras.setText("Adicionar extra");
        jButtonExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExtrasActionPerformed(evt);
            }
        });

        jTableVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Item", "Produto", "Tamanho", "Sabor 1", "Sabor 2", "Sabor 3", "Qtde", "Valor Unit", "Valor Tot"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVenda.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableVenda);
        if (jTableVenda.getColumnModel().getColumnCount() > 0) {
            jTableVenda.getColumnModel().getColumn(0).setResizable(false);
            jTableVenda.getColumnModel().getColumn(3).setResizable(false);
            jTableVenda.getColumnModel().getColumn(4).setResizable(false);
            jTableVenda.getColumnModel().getColumn(5).setResizable(false);
            jTableVenda.getColumnModel().getColumn(6).setResizable(false);
            jTableVenda.getColumnModel().getColumn(7).setResizable(false);
            jTableVenda.getColumnModel().getColumn(8).setResizable(false);
        }

        jLabelValorTot.setText("Valor total: R$");

        jTextFieldValorTot.setEditable(false);
        jTextFieldValorTot.setText("0.0");

        jLabelValorPago.setText("Valor pago: R$");

        jTextFieldValorPago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldValorPagoFocusLost(evt);
            }
        });

        jLabelTroco.setText("Troco: R$");

        jButtonEfetuarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imagens/addsell.png"))); // NOI18N
        jButtonEfetuarVenda.setText("Efetuar venda");
        jButtonEfetuarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEfetuarVendaActionPerformed(evt);
            }
        });

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imagens/back.png"))); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabelNSucos.setText("Número de sucos:");

        jTextFieldNSucos.setEditable(false);
        jTextFieldNSucos.setText("0");

        jTextFieldTroco.setEditable(false);
        jTextFieldTroco.setText("0.0");

        jTextFieldQtdExtra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldQtdExtraKeyTyped(evt);
            }
        });

        jLabel1.setText("Qtd.:");

        jLabel2.setText("Valor unit.: R$");

        jTextFieldValorUnitExtra.setEditable(false);
        jTextFieldValorUnitExtra.setText("2.00");

        jTextFieldTotalItens.setEditable(false);
        jTextFieldTotalItens.setText("0");

        jFormattedTextFieldDesconto.setText("0.0");

        jTextFieldDescontoTotal.setEditable(false);
        jTextFieldDescontoTotal.setText("0.0");

        jLabel3.setText("Desconto total: R$");

        jLabel4.setText("Total de itens:");

        jButton1.setText("Remover item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar");
        jButton2.setToolTipText("Limpa os campos referentes à adicionar extras");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imagens/cancel.png"))); // NOI18N
        jButton3.setText("Cancelar venda");
        jButton3.setToolTipText("Limpa todos os campos da venda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu1.setText("Arquivo");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imagens/logout.png"))); // NOI18N
        jMenuItem1.setText("Desconectar");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTamanho)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton250ml)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton500ml)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton750ml))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabelSabor1)
                                                .addGap(10, 10, 10)
                                                .addComponent(jComboBoxSabor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelSabor2)
                                                .addGap(10, 10, 10)
                                                .addComponent(jComboBoxSabor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabelSabor3)
                                            .addGap(10, 10, 10)
                                            .addComponent(jComboBoxSabor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabelQtd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldValorUnitSuco)
                                            .addComponent(jTextFieldQtdSuco)
                                            .addComponent(jFormattedTextFieldDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonLimpar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonAdicionarSuco, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(76, 76, 76)
                                .addComponent(jLabelExtras)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxExtras, 0, 1, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldQtdExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonExtras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldValorUnitExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelValorPago)
                                            .addComponent(jLabel3))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(jTextFieldDescontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonVoltar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3)))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelTroco, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelValorTot, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldTroco)
                                            .addComponent(jTextFieldValorTot, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldTotalItens, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelNSucos)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldNSucos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(49, 49, 49)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonEfetuarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton250ml)
                            .addComponent(jLabelTamanho)
                            .addComponent(jRadioButton500ml)
                            .addComponent(jLabelExtras)
                            .addComponent(jComboBoxExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldQtdExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jRadioButton750ml))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabelSabor1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jComboBoxSabor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSabor2)
                                    .addComponent(jComboBoxSabor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSabor3)
                                    .addComponent(jComboBoxSabor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldValorUnitExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExtras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDesconto)
                            .addComponent(jFormattedTextFieldDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldValorUnitSuco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelValorUnit))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldQtdSuco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelQtd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAdicionarSuco)
                            .addComponent(jButtonLimpar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNSucos)
                            .addComponent(jTextFieldDescontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNSucos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelValorPago)
                            .addComponent(jTextFieldValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTotalItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelValorTot)
                            .addComponent(jTextFieldValorTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTroco))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButtonVoltar)
                    .addComponent(jButtonEfetuarVenda))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        CaixaGUI janVenda = new CaixaGUI();
        janVenda.setLocationRelativeTo(null);
        janVenda.setVisible(true);
        janVenda.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExtrasActionPerformed
        if ((jTextFieldQtdExtra.getText().isEmpty()) || (jComboBoxExtras.getSelectedIndex() == 0)) {
            JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios!");
        } else {
            jTableVenda.setValueAt(j + 1, j, 0);
            jTableVenda.setValueAt(jComboBoxExtras.getSelectedItem(), j, 1);
            jTableVenda.setValueAt("-", j, 2);
            jTableVenda.setValueAt(jComboBoxExtras.getSelectedItem(), j, 3);
            jTableVenda.setValueAt("-", j, 4);
            jTableVenda.setValueAt("-", j, 5);
            jTableVenda.setValueAt(jTextFieldQtdExtra.getText(), j, 6);
            jTableVenda.setValueAt(jTextFieldValorUnitExtra.getText(), j, 7);
            float valorUnitExtra = Float.parseFloat(jTextFieldValorUnitExtra.getText());
            int qtdExtras = Integer.parseInt(jTextFieldQtdExtra.getText());
            String valorTotExtra = String.valueOf(valorUnitExtra * qtdExtras);
            jTableVenda.setValueAt(valorTotExtra, j, 8);
            j++;
            float desconto = 0;
            if (jFormattedTextFieldDesconto.getText().length() != 0) {
                desconto = Float.parseFloat(jFormattedTextFieldDesconto.getText());
            }
            float descontoTotal = Float.parseFloat(jTextFieldDescontoTotal.getText()) + desconto;
            jTextFieldDescontoTotal.setText(String.valueOf(descontoTotal));
            jFormattedTextFieldDesconto.setText("0.0");
            valorTotalVenda = valorTotalVenda + Float.parseFloat(valorTotExtra) - desconto;
            String valorTotalVenda2 = String.valueOf(valorTotalVenda);
            jTextFieldValorTot.setText(valorTotalVenda2);
            valorUnitExtra = 0;
            valorTotExtra = "0";
            if (jComboBoxExtras.getSelectedItem().equals("Biscoito")) {
                NBiscoito = NBiscoito + qtdExtras;
            } else {
                NBatata = NBatata + qtdExtras;
            }
            qtdExtras = 0;
            jTextFieldTotalItens.setText(String.valueOf(j));
        }

    }//GEN-LAST:event_jButtonExtrasActionPerformed

    private void jRadioButton250mlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton250mlActionPerformed
        jComboBoxSabor1.setEnabled(true);
        jComboBoxSabor2.setEnabled(false);
        jComboBoxSabor3.setEnabled(false);
        jComboBoxSabor2.setSelectedIndex(0);
        jComboBoxSabor3.setSelectedIndex(0);
        jTextFieldValorUnitSuco.setText("3.00");
//int tam = 1;
    }//GEN-LAST:event_jRadioButton250mlActionPerformed

    private void jRadioButton500mlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton500mlActionPerformed
        jComboBoxSabor1.setEnabled(true);
        jComboBoxSabor2.setEnabled(true);
        jComboBoxSabor3.setEnabled(false);
        jComboBoxSabor3.setSelectedIndex(0);
        jTextFieldValorUnitSuco.setText("5.00");
//int tam = 2;
    }//GEN-LAST:event_jRadioButton500mlActionPerformed

    private void jRadioButton750mlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton750mlActionPerformed
        jComboBoxSabor1.setEnabled(true);
        jComboBoxSabor2.setEnabled(true);
        jComboBoxSabor3.setEnabled(true);
        jTextFieldValorUnitSuco.setText("7.00");
//int tam = 3;
    }//GEN-LAST:event_jRadioButton750mlActionPerformed

    private void jButtonAdicionarSucoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarSucoActionPerformed
        if ((jTextFieldQtdSuco.getText().isEmpty()) || (buttonGroupTamanho.getSelection() == null)) {
            JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios!");
        } else {
            if (jRadioButton250ml.isSelected()) {
                if (jComboBoxSabor1.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios!");
                    return;
                }
                N250 = N250 + Integer.parseInt(jTextFieldQtdSuco.getText());
            }

            if (jRadioButton500ml.isSelected()) {
                if ((jComboBoxSabor1.getSelectedIndex() == 0)
                        || (jComboBoxSabor2.getSelectedIndex() == 0)) {
                    JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios!");
                    return;
                }
                N500 = N500 + Integer.parseInt(jTextFieldQtdSuco.getText());;
            }

            if (jRadioButton750ml.isSelected()) {
                if ((jComboBoxSabor1.getSelectedIndex() == 0)
                        || (jComboBoxSabor2.getSelectedIndex() == 0)
                        || (jComboBoxSabor3.getSelectedIndex() == 0)) {
                    JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios!");
                    return;
                }
                N750 = N750 + Integer.parseInt(jTextFieldQtdSuco.getText());;
            }

            int NSucos = Integer.parseInt(jTextFieldNSucos.getText());
            int NAdicionadas = Integer.parseInt(jTextFieldQtdSuco.getText());
            String novoNSucos = String.valueOf(NSucos + NAdicionadas);
            jTextFieldNSucos.setText(novoNSucos);
            jTableVenda.setValueAt(j + 1, j, 0);
            jTableVenda.setValueAt("Suco", j, 1);
            jTableVenda.setValueAt(buttonGroupTamanho.getSelection().getActionCommand(), j, 2);
            jTableVenda.setValueAt(jComboBoxSabor1.getSelectedItem(), j, 3);
            jTableVenda.setValueAt(jComboBoxSabor2.getSelectedItem(), j, 4);
            jTableVenda.setValueAt(jComboBoxSabor3.getSelectedItem(), j, 5);
            jTableVenda.setValueAt(jTextFieldQtdSuco.getText(), j, 6);
            jTableVenda.setValueAt(jTextFieldValorUnitSuco.getText(), j, 7);
            float valorUnit = Float.parseFloat(jTextFieldValorUnitSuco.getText());
            int qtdSucos = Integer.parseInt(jTextFieldQtdSuco.getText());
            String valorTotSucos = String.valueOf(valorUnit * qtdSucos);
            jTableVenda.setValueAt(valorTotSucos, j, 8);
            j++;
            float desconto = 0;
            float descontoTotal = 0;
            if (jFormattedTextFieldDesconto.getText().length() != 0) {
                desconto = Float.parseFloat(jFormattedTextFieldDesconto.getText());
            }
            descontoTotal = Float.parseFloat(jTextFieldDescontoTotal.getText()) + desconto;
            jTextFieldDescontoTotal.setText(String.valueOf(descontoTotal));
            jFormattedTextFieldDesconto.setText("0.0");
            valorTotalVenda = valorTotalVenda + Float.parseFloat(valorTotSucos) - desconto;
            String valorTotalVenda2 = String.valueOf(valorTotalVenda);
            jTextFieldValorTot.setText(valorTotalVenda2);
            NSucos = 0;
            NAdicionadas = 0;
            novoNSucos = "0";
            valorUnit = 0;
            qtdSucos = 0;
            valorTotSucos = "0";
            tamanho = "";
            jTextFieldTotalItens.setText(String.valueOf(j));
        }
    }//GEN-LAST:event_jButtonAdicionarSucoActionPerformed

    private void jTextFieldQtdSucoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQtdSucoKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldQtdSucoKeyTyped

    private void jButtonEfetuarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEfetuarVendaActionPerformed

        int op = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja efetuar a venda de:\n"
                + N250 + " sucos de 250ml\n" + N500 + " sucos de 500ml\n" + N750 + " sucos de 750ml\n"
                + NBiscoito + " biscoitos\n" + NBatata + " batatas\n" + N750 + " sucos de 750ml?\n"
                + "", "Atenção", JOptionPane.OK_CANCEL_OPTION);
        if (op == JOptionPane.OK_OPTION) {
            if((jTextFieldValorPago.getText().equals("")) || (Float.parseFloat(jTextFieldTroco.getText())<0)){
                JOptionPane.showMessageDialog(null, "Erro ao realizar venda.\nPor favor digite um valor pago suficiente para quitar o valor total.");
            }else{
            VendaDAO dao = new VendaDAO();
            Venda venda = new Venda();
            int idVenda = (dao.pegaID());

            venda.setQtdSuco250(String.valueOf(N250));
            venda.setQtdSuco500(String.valueOf(N500));
            venda.setQtdSuco750(String.valueOf(N750));
            venda.setQtdBiscoito(String.valueOf(NBiscoito));
            venda.setQtdBatata(String.valueOf(NBatata));
            venda.setDesconto(jTextFieldDescontoTotal.getText());
            venda.setValorTotal(jTextFieldValorTot.getText());

            if (jTextFieldTotalItens.getText().equals("0")) {
                JOptionPane.showMessageDialog(null, "Erro ao realizar venda.\nNenhum item a ser vendido.");
            } else {
                if (dao.criarVenda(venda)) {
                    JOptionPane.showMessageDialog(null, "Venda realizada com sucesso!");

                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao realizar venda.");
                    // + "\nErro:" + JOptionPane.ERROR_MESSAGE);
                }
            }
            ItemVendidoDAO dao2 = new ItemVendidoDAO();
            ItemVendido item = new ItemVendido();

            int totitem = Integer.parseInt(jTextFieldTotalItens.getText());
            for (int k = 0; k <= totitem; k++) {
                int IdItem = k + 1;
                if (IdItem <= j) {
                    String Especificacao = (String) jTableVenda.getModel().getValueAt(k, 1);
                    String TamanhoItem = (String) jTableVenda.getModel().getValueAt(k, 2);
                    String Sabor1 = (String) jTableVenda.getModel().getValueAt(k, 3);
                    String Sabor2 = (String) jTableVenda.getModel().getValueAt(k, 4);
                    String Sabor3 = (String) jTableVenda.getModel().getValueAt(k, 5);
                    String QtdItem = (String) jTableVenda.getModel().getValueAt(k, 6);

                    item.setIdItem(IdItem);
                    item.setIdVenda(idVenda);
                    item.setEspecificacao(Especificacao);
                    item.setTamanhoItem(TamanhoItem);
                    item.setSabor1(Sabor1);
                    item.setSabor2(Sabor2);
                    item.setSabor3(Sabor3);
                    item.setQtdItem(QtdItem);
                    dao2.vendeItem(item);
                }
            }
            idVenda++;

            N250 = 0;
            N500 = 0;
            N750 = 0;
            NBiscoito = 0;
            NBatata = 0;
            valorTotalVenda = 0;

            jComboBoxSabor1.setSelectedIndex(0);
            jComboBoxSabor1.setEnabled(false);
            jComboBoxSabor2.setSelectedIndex(0);
            jComboBoxSabor2.setEnabled(false);
            jComboBoxSabor3.setSelectedIndex(0);
            jComboBoxSabor3.setEnabled(false);
            jComboBoxExtras.setSelectedIndex(0);
            jFormattedTextFieldDesconto.setText("0.0");
            buttonGroupTamanho.clearSelection();
            jTextFieldValorUnitSuco.setText("");
            jTextFieldQtdSuco.setText("");
            jTextFieldQtdExtra.setText("");
            DefaultTableModel modelo = (DefaultTableModel) this.jTableVenda.getModel();
            int[] rows = jTableVenda.getSelectedRows();

            for (int i = 0; i < rows.length; i++) {
                modelo.removeRow(rows[i] - i);
            }

            for (int row = 0; row < modelo.getRowCount(); row++) {
                jTableVenda.setValueAt(row + 1, row, 0);
                jTableVenda.setValueAt("", row, 1);
                jTableVenda.setValueAt("", row, 2);
                jTableVenda.setValueAt("", row, 3);
                jTableVenda.setValueAt("", row, 4);
                jTableVenda.setValueAt("", row, 5);
                jTableVenda.setValueAt("", row, 6);
                jTableVenda.setValueAt("", row, 7);
                jTableVenda.setValueAt("", row, 8);
            }
            jTextFieldDescontoTotal.setText("0.0");
            jTextFieldValorTot.setText("0.0");
            jTextFieldValorPago.setText("");
            jTextFieldTroco.setText("0.0");
            jTextFieldNSucos.setText("0");
            jTextFieldTotalItens.setText("0");
            j = 0;
        }
      }
    }//GEN-LAST:event_jButtonEfetuarVendaActionPerformed

    private void jTextFieldValorPagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldValorPagoFocusLost
        float valorTotalVenda2 = Float.parseFloat(jTextFieldValorTot.getText());
        float troco = Float.parseFloat(jTextFieldValorPago.getText()) - valorTotalVenda2;
        String troco2 = String.valueOf(troco);
        jTextFieldTroco.setText(troco2);
    }//GEN-LAST:event_jTextFieldValorPagoFocusLost

    private void jTextFieldQtdExtraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQtdExtraKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldQtdExtraKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) this.jTableVenda.getModel();
        int[] rows = jTableVenda.getSelectedRows();

        String TipoProdutoRetirado = (String) jTableVenda.getValueAt(jTableVenda.getSelectedRow(), 2);
        String TipoProdutoRetirado2 = (String) jTableVenda.getValueAt(jTableVenda.getSelectedRow(), 1);
        float ValorProdutoRetirado = Float.parseFloat((String) jTableVenda.getValueAt(jTableVenda.getSelectedRow(), 8));
        int QtdProdutoRetirado = Integer.parseInt((String) jTableVenda.getValueAt(jTableVenda.getSelectedRow(), 6));

        valorTotalVenda = valorTotalVenda - ValorProdutoRetirado;
        jTextFieldValorTot.setText(String.valueOf(valorTotalVenda));

        if (TipoProdutoRetirado.equals("250ml")) {
            N250 = N250 - QtdProdutoRetirado;
            jTextFieldNSucos.setText(String.valueOf(Integer.parseInt(jTextFieldNSucos.getText()) - QtdProdutoRetirado));
        }
        if (TipoProdutoRetirado.equals("500ml")) {
            N500 = N500 - QtdProdutoRetirado;
            jTextFieldNSucos.setText(String.valueOf(Integer.parseInt(jTextFieldNSucos.getText()) - QtdProdutoRetirado));
        }
        if (TipoProdutoRetirado.equals("750ml")) {
            N250 = N750 - QtdProdutoRetirado;
            jTextFieldNSucos.setText(String.valueOf(Integer.parseInt(jTextFieldNSucos.getText()) - QtdProdutoRetirado));
        }
        if (TipoProdutoRetirado2.equals("Batata")) {
            NBatata = NBatata - QtdProdutoRetirado;
        }
        if (TipoProdutoRetirado2.equals("Biscoito")) {
            NBiscoito = NBiscoito - QtdProdutoRetirado;
        }

        for (int i = 0; i < rows.length; i++) {
            model.removeRow(rows[i] - i);
        }

        for (int row = 0; row < model.getRowCount(); row++) {
            jTableVenda.setValueAt(row + 1, row, 0);
        }
        if (j > 0) {
            j--;
        }
        jTextFieldTotalItens.setText(String.valueOf(j));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jComboBoxSabor1.setSelectedIndex(0);
        jComboBoxSabor1.setEnabled(false);
        jComboBoxSabor2.setSelectedIndex(0);
        jComboBoxSabor2.setEnabled(false);
        jComboBoxSabor3.setSelectedIndex(0);
        jComboBoxSabor3.setEnabled(false);
        jComboBoxExtras.setSelectedIndex(0);
        jFormattedTextFieldDesconto.setText("0.0");
        buttonGroupTamanho.clearSelection();
        jTextFieldValorUnitSuco.setText("");
        jTextFieldQtdSuco.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int N250 = 0;
        int N500 = 0;
        int N750 = 0;
        int NBiscoito = 0;
        int NBatata = 0;

        jComboBoxSabor1.setSelectedIndex(0);
        jComboBoxSabor1.setEnabled(false);
        jComboBoxSabor2.setSelectedIndex(0);
        jComboBoxSabor2.setEnabled(false);
        jComboBoxSabor3.setSelectedIndex(0);
        jComboBoxSabor3.setEnabled(false);
        jComboBoxExtras.setSelectedIndex(0);
        jFormattedTextFieldDesconto.setText("0.0");
        buttonGroupTamanho.clearSelection();
        jTextFieldValorUnitSuco.setText("");
        jTextFieldQtdSuco.setText("");
        jTextFieldQtdExtra.setText("");
        DefaultTableModel modelo = (DefaultTableModel) this.jTableVenda.getModel();
        int[] rows = jTableVenda.getSelectedRows();

        for (int i = 0; i < rows.length; i++) {
            modelo.removeRow(rows[i] - i);
        }

        for (int row = 0; row < modelo.getRowCount(); row++) {
            jTableVenda.setValueAt(row + 1, row, 0);
            jTableVenda.setValueAt("", row, 1);
            jTableVenda.setValueAt("", row, 2);
            jTableVenda.setValueAt("", row, 3);
            jTableVenda.setValueAt("", row, 4);
            jTableVenda.setValueAt("", row, 5);
            jTableVenda.setValueAt("", row, 6);
            jTableVenda.setValueAt("", row, 7);
            jTableVenda.setValueAt("", row, 8);
        }
        jTextFieldDescontoTotal.setText("0.0");
        jTextFieldValorTot.setText("0.0");
        jTextFieldValorPago.setText("");
        jTextFieldTroco.setText("0.0");
        jTextFieldNSucos.setText("0");
        jTextFieldTotalItens.setText("0");
        j = 0;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        LoginGUI janLogin = new LoginGUI();
        janLogin.setLocationRelativeTo(null);
        janLogin.setVisible(true);
        janLogin.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        LoginGUI janLogin = new LoginGUI();
        janLogin.setLocationRelativeTo(null);
        janLogin.setVisible(true);
        janLogin.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaixaVendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaixaVendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaixaVendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaixaVendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaixaVendaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTamanho;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAdicionarSuco;
    private javax.swing.JButton jButtonEfetuarVenda;
    private javax.swing.JButton jButtonExtras;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox jComboBoxExtras;
    private javax.swing.JComboBox jComboBoxSabor1;
    private javax.swing.JComboBox jComboBoxSabor2;
    private javax.swing.JComboBox jComboBoxSabor3;
    private javax.swing.JTextField jFormattedTextFieldDesconto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDesconto;
    private javax.swing.JLabel jLabelExtras;
    private javax.swing.JLabel jLabelNSucos;
    private javax.swing.JLabel jLabelQtd;
    private javax.swing.JLabel jLabelSabor1;
    private javax.swing.JLabel jLabelSabor2;
    private javax.swing.JLabel jLabelSabor3;
    private javax.swing.JLabel jLabelTamanho;
    private javax.swing.JLabel jLabelTroco;
    private javax.swing.JLabel jLabelValorPago;
    private javax.swing.JLabel jLabelValorTot;
    private javax.swing.JLabel jLabelValorUnit;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButton jRadioButton250ml;
    private javax.swing.JRadioButton jRadioButton500ml;
    private javax.swing.JRadioButton jRadioButton750ml;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVenda;
    private javax.swing.JTextField jTextFieldDescontoTotal;
    private javax.swing.JTextField jTextFieldNSucos;
    private javax.swing.JTextField jTextFieldQtdExtra;
    private javax.swing.JTextField jTextFieldQtdSuco;
    private javax.swing.JTextField jTextFieldTotalItens;
    private javax.swing.JTextField jTextFieldTroco;
    private javax.swing.JTextField jTextFieldValorPago;
    private javax.swing.JTextField jTextFieldValorTot;
    private javax.swing.JTextField jTextFieldValorUnitExtra;
    private javax.swing.JTextField jTextFieldValorUnitSuco;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("suco.png")));
    }
}
