package gui;


import java.awt.*;
import static java.lang.Thread.sleep;
import java.util.logging.*;
public class SplashScreen extends javax.swing.JFrame {

   
    public SplashScreen() {
        initComponents();
        setIcon();
        new Thread(){
            
            @Override
            public void run(){
                
                for(int i = 0;i<101;i++){
                    
                    try {
                        sleep(60);
                        jProgressBarSplash.setValue(i);                        
                        
                        if(jProgressBarSplash.getValue() <= 40){
                            jLabelSplash.setText("Colhendo frutas...");
                        }else if(jProgressBarSplash.getValue() <= 70){
                            jLabelSplash.setText("Retirando a água do poço...");
                        }else{
                            jLabelSplash.setText("Ligando o liquidificador...");
                        }
                        
                    } catch (InterruptedException ex) {
                        Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
    LoginGUI  janLogin = new LoginGUI();
    janLogin = new LoginGUI();
    janLogin.setLocationRelativeTo(null);
    janLogin.setVisible(true);
    janLogin.setResizable(false);
    dispose();
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBarSplash = new javax.swing.JProgressBar();
        jLabelSplash = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jProgressBarSplash.setStringPainted(true);
        getContentPane().add(jProgressBarSplash);
        jProgressBarSplash.setBounds(10, 380, 670, 20);

        jLabelSplash.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSplash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelSplash);
        jLabelSplash.setBounds(10, 340, 670, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imagens/Balde dos sucos splash.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 140, 530, 110);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imagens/suco3.gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 60, 220, 270);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/imagens/florestaslpash.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 430);

        setSize(new java.awt.Dimension(689, 410));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelSplash;
    private javax.swing.JProgressBar jProgressBarSplash;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("suco.png")));
    }
}
